Update integration.gitlab-ci.yml

diff --git a/integration.gitlab-ci.yml b/integration.gitlab-ci.yml
--- a/integration.gitlab-ci.yml
+++ b/integration.gitlab-ci.yml
@@ -26,7 +26,7 @@ checkout:
     - export COMMIT_ID=$(cat commit_hash.txt)
     - export ZIP_FILE_NAME="${ARTIFACT_ID}-${COMMIT_ID}.zip"
   rules:
-    - if: '$CI_COMMIT_REF_NAME'
+    - if: '$CI_COMMIT_REF_NAME !~ /^skip\/.*$/'
       when: always
 
 fetch_Packages:
@@ -36,7 +36,7 @@ fetch_Packages:
   script:
     - flutter pub get
   rules:
-    - if: '$CI_COMMIT_REF_NAME'
+    - if: '$CI_COMMIT_REF_NAME !~ /^skip\/.*$/'
       when: always
 
 test:
@@ -46,7 +46,7 @@ test:
   script:
     - flutter test
   rules:
-    - if: '$CI_COMMIT_REF_NAME'
+    - if: '$CI_COMMIT_REF_NAME !~ /^skip\/.*$/'
       when: always
 
 build:
@@ -55,8 +55,11 @@ build:
     - docker-flutter
   script:
     - flutter build apk --release --build-name="${BRANCH_NAME}" --build-number="${BUILD_NUMBER}"
+  artifacts:
+    paths:
+      - build/app/outputs/flutter-apk/app-release.apk
   rules:
-    - if: '$CI_COMMIT_REF_NAME'
+    - if: '$CI_COMMIT_REF_NAME !~ /^skip\/.*$/'
       when: always
 
 package:
@@ -75,7 +78,7 @@ package:
     paths:
       - artifact-*.zip
   rules:
-    - if: '$CI_COMMIT_REF_NAME'
+    - if: '$CI_COMMIT_REF_NAME !~ /^skip\/.*$/'
       when: always
 
 upload:
@@ -92,7 +95,7 @@ upload:
     - ls -l ${ZIP_FILE_NAME}  # Verify file existence
     - curl -u ${NEXUS_CREDENTIALS_ID} --upload-file "${ZIP_FILE_NAME}" "${UPLOAD_URL}"
   rules:
-    - if: '$CI_COMMIT_REF_NAME'
+    - if: '$CI_COMMIT_REF_NAME !~ /^skip\/.*$/'
       when: always
 
 distribute:
@@ -104,15 +107,22 @@ distribute:
   script:
     - apkPath="build/app/outputs/flutter-apk/app-release.apk"
     - tagName="v${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
+    - echo "Checking for APK file at $apkPath"
+    - ls -l build/app/outputs/flutter-apk/ || true  # Affiche les fichiers dans le répertoire
     - |
-      [ -f "$apkPath" ] && echo "APK file exists. Proceeding with distribution." && \
-      curl -F "ipa=@${apkPath}" \
-           -F "release_notes=Branch: ${CI_COMMIT_REF_NAME} - Build ${CI_PIPELINE_ID} - Commit ${COMMIT_ID}" \
-           -F "distribution_group=flutter-app" \
-           -H "X-API-Token: 79aabd068b99a4b35b3688e39b1a69ff6eec38e6" \
-           https://api.appcenter.ms/v0.1/apps/sghaier-fss.u-sfax.tn/flutter-app/release_uploads || \
-      (echo "APK file does not exist at $apkPath. Distribution aborted." && exit 1)
+      if [ -f "$apkPath" ]; then
+        echo "APK file exists. Proceeding with distribution."
+        curl -F "ipa=@${apkPath}" \
+             -F "release_notes=Branch: ${CI_COMMIT_REF_NAME} - Build ${CI_PIPELINE_ID} - Commit ${COMMIT_ID}" \
+             -F "distribution_group=flutter-app" \
+             -H "X-API-Token: 79aabd068b99a4b35b3688e39b1a69ff6eec38e6" \
+             https://api.appcenter.ms/v0.1/apps/sghaier-fss.u-sfax.tn/flutter-app/release_uploads
+      else
+        echo "APK file does not exist at $apkPath. Distribution aborted."
+        exit 1
+      fi
   rules:
-    - if: '$CI_COMMIT_REF_NAME'
+    - if: '$CI_COMMIT_REF_NAME !~ /^skip\/.*$/'
       when: always
+
 
