Update integration.gitlab-ci.yml

diff --git a/integration.gitlab-ci.yml b/integration.gitlab-ci.yml
--- a/integration.gitlab-ci.yml
+++ b/integration.gitlab-ci.yml
@@ -3,16 +3,17 @@ stages:
   - fetch_Packages
   - test
   - build
+  - distribute
   - package
   - upload
-  - distribute
+  
 
 variables:
   NEXUS_CREDENTIALS_ID: 'nexus-jenkins'
   NEXUS_URL: 'https://nexus.u-cloudsolutions.xyz'
   NEXUS_REPOSITORY: 'student-repository'
   GROUP_ID: 'com.artificial.Flutter'
-  ARTIFACT_ID: 'project-flutter'
+  ARTIFACT_ID: 'artifact'
   ZIP_FILE_NAME: '${ARTIFACT_ID}-${COMMIT_ID}.zip'
   COMMIT_ID: $(git rev-parse --short HEAD)
 
@@ -67,6 +68,55 @@ build:
     - if: '$CI_COMMIT_REF_NAME == $TARGET_BRANCH'
       when: always
 
+distribute:
+  stage: distribute
+  tags:
+    - docker-flutter
+  dependencies:
+    - build
+  script:
+    - apk update && apk add jq  # Installation de jq
+    - apkPath="build/app/outputs/flutter-apk/app-release.apk"
+    - tagName="v${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
+    - echo "Checking for APK file at $apkPath"
+    - ls -l build/app/outputs/flutter-apk/ || true
+    - |
+      if [ -f "$apkPath" ]; then
+        echo "APK file exists. Proceeding with distribution."
+        
+        # Crée une session d'upload sur App Center
+        UPLOAD_RESPONSE=$(curl -X POST \
+          -H "X-API-Token: 79aabd068b99a4b35b3688e39b1a69ff6eec38e6" \
+          https://api.appcenter.ms/v0.1/apps/sghaier-fss.u-sfax.tn/flutter-app/release_uploads)
+
+        UPLOAD_ID=$(echo "$UPLOAD_RESPONSE" | jq -r '.upload_id')
+        UPLOAD_URL=$(echo "$UPLOAD_RESPONSE" | jq -r '.upload_url')
+
+        if [ -n "$UPLOAD_URL" ]; then
+          echo "Starting multipart upload..."
+          curl -X PUT "$UPLOAD_URL" \
+            -F "ipa=@${apkPath};type=application/vnd.android.package-archive" || \
+          (echo "Failed to upload APK file. Distribution aborted." && exit 1)
+
+          # Finaliser l'upload sur App Center
+          curl -X PATCH \
+            -H "X-API-Token: 79aabd068b99a4b35b3688e39b1a69ff6eec38e6" \
+            https://api.appcenter.ms/v0.1/apps/sghaier-fss.u-sfax.tn/flutter-app/release_uploads/$UPLOAD_ID \
+            -d '{"status": "committed"}' || \
+          (echo "Failed to commit APK file. Distribution aborted." && exit 1)
+        else
+          echo "Failed to initiate upload. Distribution aborted."
+          exit 1
+        fi
+      else
+        echo "APK file does not exist at $apkPath. Distribution aborted."
+        exit 1
+      fi
+  rules:
+    - if: '$CI_COMMIT_REF_NAME == $TARGET_BRANCH'
+      when: always
+
+
 package:
   stage: package
   tags:
@@ -95,65 +145,15 @@ upload:
   script:
     - echo "Determining commit ID..."
     - COMMIT_ID=$(git rev-parse --short HEAD)
-    - ZIP_FILE_NAME="project-flutter-${COMMIT_ID}.zip"
+    - ZIP_FILE_NAME="artifact-${COMMIT_ID}.zip"
     - echo "Uploading ${ZIP_FILE_NAME} to Nexus..."
     - UPLOAD_URL="${NEXUS_URL}/repository/${NEXUS_REPOSITORY}/${GROUP_ID//./\/}/${ARTIFACT_ID}/${COMMIT_ID}/${ZIP_FILE_NAME}"
     - pwd  # Print working directory
     - find . -name "*.zip"  # Find ZIP files
     - ls -l ${ZIP_FILE_NAME}  # Verify file existence
-    - curl -u ${NEXUS_CREDENTIALS_ID} --upload-file "${ZIP_FILE_NAME}" "${UPLOAD_URL}"
+    - curl -u wissem:3FqNnJ6XzF --upload-file "${ZIP_FILE_NAME}" "${UPLOAD_URL}"
+
+
   rules:
     - if: '$CI_COMMIT_REF_NAME == $TARGET_BRANCH'
       when: always
-
-distribute:
-  stage: distribute
-  tags:
-    - docker-flutter
-  dependencies:
-    - build
-  script:
-    - apkPath="build/app/outputs/flutter-apk/app-release.apk"
-    - tagName="v${CI_PIPELINE_ID}-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
-    - echo "Checking for APK file at $apkPath"
-    - ls -l build/app/outputs/flutter-apk/ || true
-    - |
-      if [ -f "$apkPath" ]; then
-        echo "APK file exists. Proceeding with distribution."
-        
-        # Crée une session d'upload sur App Center
-        UPLOAD_ID=$(curl -X POST \
-          -H "X-API-Token: 79aabd068b99a4b35b3688e39b1a69ff6eec38e6" \
-          https://api.appcenter.ms/v0.1/apps/sghaier-fss.u-sfax.tn/flutter-app/release_uploads \
-          | jq -r '.upload_id')
-
-        UPLOAD_URL=$(curl -X POST \
-          -H "X-API-Token: 79aabd068b99a4b35b3688e39b1a69ff6eec38e6" \
-          https://api.appcenter.ms/v0.1/apps/sghaier-fss.u-sfax.tn/flutter-app/release_uploads \
-          | jq -r '.upload_url')
-
-        if [ -n "$UPLOAD_URL" ]; then
-          echo "Starting multipart upload..."
-          curl -X PUT "$UPLOAD_URL" \
-            -F "ipa=@${apkPath}" || \
-          (echo "Failed to upload APK file. Distribution aborted." && exit 1)
-
-          # Finaliser l'upload sur App Center
-          curl -X PATCH \
-            -H "X-API-Token: 79aabd068b99a4b35b3688e39b1a69ff6eec38e6" \
-            https://api.appcenter.ms/v0.1/apps/sghaier-fss.u-sfax.tn/flutter-app/release_uploads/$UPLOAD_ID \
-            -d '{"status": "committed"}' || \
-          (echo "Failed to commit APK file. Distribution aborted." && exit 1)
-        else
-          echo "Failed to initiate upload. Distribution aborted."
-          exit 1
-        fi
-      else
-        echo "APK file does not exist at $apkPath. Distribution aborted."
-        exit 1
-      fi
-  rules:
-    - if: '$CI_COMMIT_REF_NAME == $TARGET_BRANCH'
-      when: always
-
-
